#!/bin/sh

check_output() {
    cmp .output.$1 .expected_output.$1 2>/dev/null >/dev/null
    if [ $? -eq 0 ]
    then
        echo "PASSED"
        #rm $1 $2
    else
        echo "FAILED"
        echo "Output from tritontalk binary is in file: .output.$1"
        echo "Expected output is in file: .expected_output.$1"
        echo "Debug output from tritontalk binary is in file: .debug_output.$1"
    fi
    echo
}

echo "###########################################################################"
echo "NOTE: Guidelines for using this script:"
echo "      - Tests check output written to stdout only."
echo "        If you have debug output in stdout, it may cause test failures."
echo "      - This is not a comprehensive set of test cases."
echo "        It is intended to help you do basic checks on your project."
echo "      - If your program fails any test, it will print the output files"
echo "        generated by your program and the output expected for the test case."
echo "      - The script should take about 20 seconds to complete."
echo "###########################################################################"
echo
echo
echo "Rebuilding tritontalk..."
make clean; make -j4 tritontalk
echo "Done rebuilding tritontalk"
echo

## My test
echo -n "My test : Sending 300 packets (with corrupt probability of 40% and drop rate of 40%) and expecting receiver to print them out in order(longer sleep time at last for handle time out frames): "
(sleep 0.5; for i in `seq 1 300`; do echo "msg 0 0 Packet: $i"; sleep 0.1; done; sleep 60; echo "exit") | ./tritontalk -c 0.4 -d 0.4 -r 1 -s 1 > .output.my 2> .debug_output.my

(for i in `seq 1 300`; do echo "<RECV_0>:[Packet: $i]"; done) > .expected_output.my

check_output my
echo
echo "Completed test cases"


